### ISSUE TITLE
Geofences not triggered / http requests not sent

### ISSUE THREAD

**Issue by kimar** [Geofancy/android-app#6]
Seems like entering / leaving fences is not worknig correctly. The last time I ran the App is almost a year ago and I've had only an old Samsung test device those days.

**Comment by francisdb** [comment]
Works for me now, still needs some tweaks but we can fix that along the way

**Comment by francisdb** [comment]
@kimar please close

**Comment by kimar** [comment]
Awesome @francisdb thx!
